### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by kaskol984** [meserak86/QWERX#2]
Witam
Masz mozliwosc dodania niemieckich kanałow do tv guide? sky sport itp.
Z gory dzieki za odp.
Pozdro

**Comment by plumers** [comment]
Witam autora - brakuje w sekcji sport gregs -TVPsport wtyczka z ramicmod repository -Albo własna- aby działało piękniej niż obecnie - ogólnie WOW super robota :D

**Comment by meserak86** [comment]
ramic umarl
