### ISSUE TITLE
Problem z Polską Telewizją(OnlyPL)

### ISSUE THREAD

**Issue by hippolsrp** [meserak86/QWERX#3]
Witam, wczorajszego dnia chciałem sobie obejrzeć Ligę Mistrzów na kanale Canal+, włączam sobie program Kodi, wchodzę w telewizję ONLYPL, pózniej M-TV Guide EPG, naciskam na Canal+ i nic się nie dzieję, zakręci się kółko, a później nic.
Dodam jeszcze, że inne kanały działają normalnie.
Na początku myślałem, że to jakieś przeciążenie, ale wchodzę dzisiaj rano i nadal nie działa.
Z góry dzięki za odpowiedz.

**Comment by hippolsrp** [comment]
już działa, dzięki.

**Comment by meserak86** [comment]
jesli w buildzie sa zostawione jakies loginy hasla listy itd, to nie placzcie ze nie dziala costam, bo wstawiam to tylko jak od ludzi to dostaje do uzytku publicznego, osobiscie nie korzystam z TV polskiej w kodi wiec tak naprawde mnie to rybka czy w buildzie to chodzi czy nie, i czy dana tv ma problemy:D
