### ISSUE TITLE
Użycie w buildzie 2

### ISSUE THREAD

**Issue by Rawen4** [meserak86/QWERX#4]
Witaj! Użyłem kilku dodatków z Twojego repozytorium w moim buildzie. Mam nadzieję że nie będzie to problem, bo nie wiedziałem że trzeba prosić o pozwolenie na wykorzystanie. Oczywiście sam build jak i dodatki w nim zawarte są darmowe, więc mam nadzieję że odpowiedz będzie pozytywna.
Pozdrawiam.

**Comment by meserak86** [comment]
jak build nie bedzie platny ani sprzedawany z boxami to nie ma problemu

**Comment by Rawen4** [comment]
Ok dzięki. Build jest bezpłatny i nie sprzedawany z boxami. Przeglądałem tez wasze buildy, dobra robota. Pozdrawiam.
