### ISSUE TITLE
Problemy z m-TV Guide v8.3.1  i IPTV Simple Client w QWER v9.5.3

### ISSUE THREAD

**Issue by yorg1952** [meserak86/QWERX#7]
Zainstalowałe QWER  build v9.5.3 w wersji Full na jednym komputerze i Simply na drugim,
na Windws 7 i 10.
W v.9.5.2 do pewnego czasu działało mi m-TV Guide i również wtyczka PVR IPTV. poprawnie wybierała programy. Czy teraz już w m-TV Guide, w tej najnowszej wersji, będzie tylko dostęp do darmowych kont
w WizjaTv i GoldVod . Czy wielkoduszność pabloo255 i mariuszek32 w ustawieniach wtyczki
już się nie powtórzy i w związku z tym trzeba będzie pukać do mods-kodi  by mieć działające m-TV Guide wraz z epg. Jestem gotów wspierać Pana trud przy buildzie QWER jakąś skromną stałą miesięczną kwotą..
A może inni użytkownicy też by się dorzucili ? Tylko, kurczę, niech ten "Kodik" z tym buildem działa mi lepiej.
W PVR IPTV Simple Client kanały się zawieszają a po minucie działania zrywają całkiem.
Brakuje mi pomysłów i "wiedzy" co z tym zrobić, żeby działało zadowalająco poprawnie.
Będę wdzięczny za jakieś podpowiedzi. Jak wygodnie, może być tak jak ostatnio, również na oya@op.pl
Pozdrawiam serdecznie.

**Comment by meserak86** [comment]
za moj build sie nie  placi, jak mi cos potrzebanp test IPTV albo haselka to wolam ze potrzebuje na FB na grupie albo zrobie zbiorke np na sprzet jesli cos bym potrzebowal zeby do tego nie dokladac, co do pvr simple i m-tv to obecnie jest konflikt  grupy mods-userzy  do tego gold sie przebudowuje a wizja juz sie przebudowala i wizja ma zabezpieczenia i kazdy jak chce ogladac wizje to se musi sam kupic, a co bedzie z goldem to nie wiem, narazie do buildu sa wsadzone listy darmowe z pestbina, jak nie dziala to wstawie inna jesli cos dostane, jesli nie to sami we lasnymzakresie sie wawcie, ja robie build, a to ze zostawie jakies haslo wlogowane albo liste to juz sprawa dobrych ludzi ktorzy to podrzucaja i tyle, jak sie nie znajdzie takowy to se sami bedziecie kombinowac, ja i tak nie korzystam z IPTV zadnej praktycznie poza testami

**Comment by meserak86** [comment]
co do kodi to na kodi 18 leila pvr i  iptv bedzie cielo na niektorych boxach samo z siebie strasznie, na kompie tez czasami potrafi bo 18 to jeszcze alfa... 17,5 jest najstabilniejsze, a kazda IPTV czasem zacina to trzeba wylaczyc i jeszcze raz wlaczyc ten sam kanal
